env:
  global:
  - TERM=dumb

language: java
jdk: oraclejdk8

install: true

script:

- mkdir my-app
- cd my-app/
- gradle wrapper --gradle-version=4.6
- ./gradlew init --type=java-application --dsl kotlin
- ./gradlew clean build
- java -jar build/libs/*.jar

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
