env:
  global:
  - TERM=dumb

language: java
jdk: oraclejdk8

install: true

script:
- mkdir my-app
- cd my-app/
- gradle wrapper --gradle-version=4.6
- bash gradlew init --type=java-application --dsl kotlin
- bash gradlew clean build
- java -cp build/libs/*.jar App

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
